### ISSUE TITLE
TMS9918A outputs a blank blue screen when running FUZIX via rc2014_sdl2

### ISSUE THREAD

**Issue by ry755** [EtchedPixels/EmulatorKit#44]
Hi! I'm attempting to run FUZIX on an emulated RC2014 with a TMS9918A. FUZIX seems to boot correctly, if I disable the TMS9918A and PS/2 emulation then it boots to a login prompt over the SIO. But when I pass the `-T` and `-P` options to enable the TMS9918A and PS/2, I just get a blank blue screen.

Here is the exact output:
```
[ry@fox-tower EmulatorKit]$ ./rc2014_sdl2 -s -r RCZ80_std.rom -b -T -P -i emu-ide.img
INVALID(0xFF)


RomWBW HBIOS v3.2.1, 2023-04-14

RCBus [RCZ80_std] Z80 @ 7.372MHz
0 MEM W/S, 1 I/O W/S, INT MODE 1, Z2 MMU
512KB ROM, 512KB RAM
ROM VERIFY: 00 00 00 00 PASS

SIO0: IO=0x80 SIO MODE=115200,8,N,1
SIO1: IO=0x82 SIO MODE=115200,8,N,1
DSRTC: MODE=STD IO=0xC0 NOT PRESENT
MD: UNITS=2 ROMDISK=384KB RAMDISK=256KB
FD: MODE=RCWDC IO=0x50 NOT PRESENT
IDE: IO=0x10 MODE=RC
IDE0: 8-BIT LBA BLOCKS=0x00013150 SIZE=38MB
IDE1: NO MEDIA
PPIDE: IO=0x20 PPI NOT PRESENT

Unit        Device      Type              Capacity/Mode
----------  ----------  ----------------  --------------------
Char 0      SIO0:       RS-232            115200,8,N,1
Char 1      SIO1:       RS-232            115200,8,N,1
Disk 0      MD0:        RAM Disk          256KB,LBA
Disk 1      MD1:        ROM Disk          384KB,LBA
Disk 2      IDE0:       Hard Disk         38MB,LBA
Disk 3      IDE1:       Hard Disk         --


RCBus [RCZ80_std] Boot Loader

Boot [H=Help]: 2

Booting Disk Unit 2, Slice 0, Sector 0x00000000...

Volume "Fuzix WBW Loader" [0xF200-0xF400, entry @ 0xF200]...FDC DOR 0C [AT/EISA DMA DSEN DSEL0]
CCINVALID(0xFF)
INVALID(0xFF)
FUZIX version 0.4
Copyright (c) 1988-2002 by H.F.Bower, D.Braun, S.Nitschke, H.Peraza
Copyright (c) 1997-2001 by Arcady Schekochikhin, Adriano C. R. da Cunha
Copyright (c) 2013-2015 Will Sowerbutts <will@sowerbutts.com>
Copyright (c) 2014-2023 Alan Cox <alan@etchedpixels.co.uk>
Devboot
RomWBW 3.2 on an RC2014@7MHz.
TMS9918A detected at 0x98.
PS/2 self test: FF
PS/2 Keyboard at 0xBB
Switching to video output.
```

Disabling only the PS/2 emulation makes it boot to a login prompt over the SIO, yet the TMS9918A output is still blue.

This is using a freshly built disk image that I built locally. I haven't tried your disk image from fuzix.org yet as it was taking a over an hour to download :P

Here is what the blue screen looks like:
![screenshot](https://github.com/EtchedPixels/EmulatorKit/assets/23299242/1dedd7be-5e71-45e0-9c0c-9c8408ec7adb)

I wasn't sure whether to file this issue in this repo or in the main FUZIX repo as I don't know where the error is.

**Comment by ry755** [comment]
After doing some additional testing it appears to be an issue with FUZIX., not the emulator. Recompiling RomWBW with support for the TMS9918A, I can have it switch the bootloader and CP/M output to the display, but booting FUZIX still gives me this blue screen.

**Comment by EtchedPixels** [comment]
Build defaults. The platform-rc2014/config.h file defaults to including PROPGFX support as a first console (and also to extreme mode). I will change the defaults to sane ones.
