### ISSUE TITLE
Platform wishlist

### ISSUE THREAD

**Issue by RXJpawo** [EtchedPixels/EmulatorKit#45]
If there is an wishlist on new platforms, I'd like to add one platform.
(Sadly, I'm not skilled enough to add it myself)

My suggestion is Microprofessor MPF-1.
https://en.wikipedia.org/wiki/Micro-Professor_MPF-I
I have the actual HW and manuals, I can read out the ROM:s and supply with all the documentation.

One complicating fact is the lack of serial monitor and the UI is a hex keyboard and 7-segment LED's.

**Comment by EtchedPixels** [comment]
There isn't . Platforms get added because I have a need for one or because someone contributes it.
