### ISSUE TITLE
Pull requests/changes

### ISSUE THREAD

**Issue by peterw8102** [EtchedPixels/EmulatorKit#46]
Hi, I've not contributed to someone else's public project before so no idea what the etiquette is. I have code changes to better support my z80retro project on a branch of a local clone of this repo. I don't have permission to push that to this repo to submit a pull request. What do I do?

**Comment by EtchedPixels** [comment]
Pull request is fine, email is fine (etchedpiels@gmail.com) in fact often easier.

Alan
